version: '3.8'

services:

  sparrow:
    image: soulteary/sparrow
    container_name: sparrow
    restart: always
    environment:
      # [Basic Settings]
      # => The ChatGPT Web Client Domain
      WEB_CLIENT_HOSTNAME: "https://your-domian"
      # => Service port, default: 8091
      # APP_PORT: 8091
      # => response generate speed: 1x ~ 99x
      # RESPONSE_SPEED: 1

      # [Advanced Settings] *optional
      # => Enable the new UI
      # FEATURE_NEW_UI: true
      # => Enable history list
      # ENABLE_HISTORY_LIST: true
      # => Enable i18n
      # ENABLE_I18N: true
      # => Enable the data control
      # ENABLE_DATA_CONTROL: true
      # => Enable the model switch
      # ENABLE_MODEL_SWITCH: true

      # [Plugin Settings] *optional
      # => Enable the plugin
      # ENABLE_PLUGIN: true
      # => Enable the plugin browsing
      # ENABLE_PLUGIN_BROWSING: true
      # => Enable the plugin code interpreter
      # ENABLE_PLUGIN_CODE_INTERPRETER: true

      # [Misc Settings] *optional
      # => Enable the official model
      # ENABLE_OPENAI_OFFICIAL_MODEL: true
      # => Only Enable the 3.5 model
      # ENABLE_OPENAI_ONLY_3_5: false

      # [Private OpenAI API Server Settings] *optional
      # => Enable OpenAI 3.5 API
      # ENABLE_OPENAI_API: true
      # => OpenAI API Key
      # OPENAI_API_KEY: "sk-abcdefg"
      # => Enable OpenAI API Proxy
      # OPENAI_API_PROXY_ENABLE: false
      # => OpenAI API Proxy Address, eg: `"http://127.0.0.1:1234"` or ""
      # OPENAI_API_PROXY_ADDR: ""

      # [Private Midjourney Server Settings] *optional
      # => Enable Midjourney
      # ENABLE_MIDJOURNEY: true
      # => Enable Midjourney Only
      # ENABLE_MIDJOURNEY_ONLY: false
      # => Midjourney API Key
      # MIDJOURNEY_API_SECRET: "your-secret"
      # => Midjourney API Address, eg: `"ws://...."`
      # MIDJOURNEY_API_ADDR: "ws://localhost:8092/ws"

      # [Private Midjourney Server Settings] *optional
      # => Enable FlagStudio
      # ENABLE_FLAGSTUDIO: true
      # => FlagStudio API Key
      # FLAGSTUDIO_API_KEY: "your-flagstudio-api-key"

    logging:
        driver: "json-file"
        options:
            max-size: "10m"

# use your network as you like
#     networks:
#       - traefik

# networks:
#   traefik:
#     external: true